### ISSUE TITLE
I saw your issue on ingress-nginx repo and can't understand anything there..!

### ISSUE THREAD

**Issue by sahilrajput03** [Vyom-Yadav/nginx-ingress-configuration-tutorial#1]
Hey buddy can you please exaplain how your code below works for (in terms of link1, link2 and link3) i.e., how the path rewrite happening there?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /link2/link3/
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: tut-ingress
  namespace: default
spec:
  rules:
    - host: tutorial.com
      http:
        paths:
          - path: /link1/
            pathType: Prefix
            backend:
              service:
                name: nginx-ingress-tut-service
                port:
                  number: 8080
```
